server: #端口如果不配默认8080
  port: 8098
  servlet: #dispather
    #servlet的监听路径，默认为: /
    context-path: /oes


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_exam_system?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
  #redis配置
  redis:
    #是否开启redis缓存 true开启 false关闭
    open: true
    #Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    password:
    jedis:
      pool:
        #连接池最大连接数（使用0表示没有限制）
        max-active: 0
        #连接池最大阻塞等待时间（使用0表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 100
        #连接池中的最小空闲连接
        min-idle: 50
        #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
        maxTotal: 500
    #连接超时时间（毫秒）
    timeout: 3000
    #在空闲时检查有效性, 默认false
    testWhileIdle: true
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/Pages/
    cache: false
    mode: HTML
    suffix: .html

  jms:
    pub-sub-domain: false
    #点对点模式，true为发布订阅模式
  aop:
    proxy-target-class: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #不配置这个会让springfox异常。。。
  mail:
    host: smtp.office365.com
    username: 6543x1@outlook.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587
logging:
  level:
    root: debug
    # 配置日志输出位置
  file:
    name: logs/thisProject.log

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.jessie.onlineexaminationsystem.domain
#  type-enums-package: com.jessie.campusmutualassist.entity.myEnum
# 分页配置
pagehelper:
  helper-dialect: mysql #配置所使用的数据库类型
  reasonable: true #当输入不合理的页数，返回第一页（小于0）或最后一页（大于最后一页）
  support-methods-arguments: true
  params: count=countSql
  autoRuntimeDialect: true

springfox:
  documentation:
    swagger-ui:
      enabled: true #上线到服务器后应该予以关闭
knife4j:
  basic:
    enable: true
  setting:
    enableOpenApi: true



